# Generated by Django 4.2.4 on 2023-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Pharma', 'Pharma')], max_length=20)),
                ('country', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[['Male', 'Male'], ['Female', 'Female'], ['Others', 'Others']], max_length=20)),
            ],
        ),
    ]
