# Generated by Django 4.2.4 on 2023-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_emp_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
