# Generated by Django 4.2.4 on 2023-12-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('standard', models.IntegerField()),
                ('roll_no', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
